
printWidth: 80
tabWidth: 2
useTabs: false
semi: true
singleQuote: true
quoteProps: preserve
trailingComma: all
bracketSpacing: true
arrowParens: always
overrides:
  - files: '*.sass'
    options:
      singleQuote: false
  - files: '*.html'
    options:
      printWidth: 9999