version: "3.9"  # optional since v1.27.0

services:
  message-bus:
    image: rabbitmq:3
    container_name: 'message-bus'
    ports:
        - 5672:5672
        - 15672:15672

  webapi:
    image: mendasium/tasque-backend
    container_name: webapi
    ports:
      - "5000:5000"
    env_file:
      - ./.env/backend.env
    logging:
      driver: "json-file"
      options:
        max-size: "10m"
        max-file: "5"
    # volumes:
      # - .:/ log volume!
    depends_on:
      - message-bus
      
  notifications:
    image: mendasium/tasque-notiifications
    container_name: notifications
    ports:
      - "5001:5001"
    env_file:
      - ./.env/notifications.env
    logging:
      driver: "json-file"
      options:
        max-size: "10m"
        max-file: "5"
    # volumes:
      # - .:/ log volume!
    depends_on:
      - message-bus

  frontend:
    image: mendasium/tasque-frontend
    container_name: frontend
    ports:
      - "80:80"
      - "443:443"
    env_file:
      - ./.env/frontend.env
    logging:
      driver: "json-file"
      options:
        max-size: "10m"
        max-file: "5"
    depends_on:
      - notifications
      - webapi

# volumes:
#   logvolume01: {}
